pipeline {
    agent any
    environment {
        REPO = "s10-ai-image-sub2/S10P22C202"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage("Build") {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker build -t ${DOCKER_USER_ID}/ai ForMyBaby/ai"
                    }
                }
            }
        }
        stage("Login") {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                    sh """
                        set +x
                        echo $DOCKER_USER_PASSWORD | docker login -u $DOCKER_USER_ID --password-stdin
                        set -x
                    """
                }
            }
        }
        stage("Tag and Push") {
            steps {
                script {
                     withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker push ${DOCKER_USER_ID}/ai"
                     }
                }
            }
        }
        // stage('Prune old images'){
        //     steps{
        //         script{
        //         }
        //     }
        // }
        stage('Pull') {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        sh "docker pull ${DOCKER_USER_ID}/ai"
                    }
                }
            }
        }
        stage('Up') {
            steps {
                script {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD']]) {
                        try{
                            sh "docker stop -f ai || true"
                            sh "docker rm -f ai || true"
                            sh "docker run -d --name ai -p 8083:3002 ${DOCKER_USER_ID}/ai"
                        } catch (Exception e){
                            sh "docker restart ai"
                        }
                    }
                }
            }
        }
    }

post {
        success {
            script {
                mattermostSend (color: 'good', 
                message: "AI 배포 성공   :cat_jump: :loopy_happy: :bboong: ",
                )
            }
        }
        failure {
            script {
                mattermostSend (color: 'danger', 
                message: "AI 배포 실패   :cry_tom: :cryingloopy: :cryingpatamon: "
                )
            }
        }
    }




//     post {
//         always {
//             script {
//                 def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
//                 def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
//                 mattermostSend (color: 'good',
//                         message: "빌드 ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
//                         endpoint: 'https://meeting.ssafy.com/hooks/q4qjarpscbf9pme4f46yiojzfe',
//                         channel: 'C107-Jenkins'
//                 )
//             }
//         }
//     }
}
