
spring:
  #db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j10c202.p.ssafy.io:3307/formybaby?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  #oauth2
  oauth:
    kakao:
      client_id: f9d3aa3c4d425c0ad175a6b95e366769 # REST API ?
      redirect_uri: "http://localhost:3000/oauth/redirected/kakao"
      client_secret: Mx4luiTuOBM8RAuJRU9AZ0UJdGtQrRVh
      scope: name, account_email, profile_image
  #redis
  data:
    redis:
      host: j10c202.p.ssafy.io # Redis 서버의 공개 IP 주소
      port: 6379
      password: imok202!
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIA2UC3BWP55UET3D4E
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: formybaby-bucket
    stack:
      auto: false
