spring:
  #db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/formybaby?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
  #batch
  batch:
    job:
      name: createHealth
    jdbc:
      initialize-schema: always
  #jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  #oauth2
  oauth:
    kakao:
      client_id: f9d3aa3c4d425c0ad175a6b95e366769 # REST API ?
      redirect_uri: "http://localhost:3000/oauth/redirected/kakao"
      client_secret: Mx4luiTuOBM8RAuJRU9AZ0UJdGtQrRVh
      scope: name, account_email, profile_image
#  redis
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}
#      lettuce:
#        pool:
#          max-idle: 8
#          min-idle: 0
#          max-active: 8
#          max-wait: -1
